import PredictProvider from "@/components/providers/predict";
import "./globals.css";
import { Inter } from "next/font/google";
import { ThemeProvider } from "@/components/providers/theme";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Digit prediction",
  description: "Generated by create next app to predict digit number by using CNN.",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange >
              <PredictProvider>
                {children}
              </PredictProvider>
            </ThemeProvider>
        </body>
    </html>
  );
}
