import PredictProvider from "@/components/providers/predict";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Digit prediction",
  description: "Generated by create next app to predict digit number by using CNN.",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <PredictProvider>
          {children}
        </PredictProvider>
        </body>
    </html>
  );
}
