import Predict from "@/components/predict";
import Wrapper from "@/components/wrapper";

export default function Home() {
  return (
    <div className="w-full h-full flex flex-col justify-start items-center pt-10 relative">
      <div className="text-4xl font-bold">
        Digit prediction
      </div>
      <div className="text-2xl mb-10">
        Generated by create next app to predict digit number by using CNN.
      </div>
        <Wrapper />
        <Predict />
    </div>
  );
}